- src/execution/index.ts
- src/orchestrator/registry.ts
> feat: add default account access list

- .github/workflows/ci.yaml
- .github/workflows/main.yaml
- src/accounts/index.ts
- test/orchestrator.ts
Fixes e2e tests by cleaning up the build directory (`dist`) before running them. This somehow fixes the import path resolution for the orch mock.
> Fix e2e tests

- .changeset/fine-squids-turn.md
- src/execution/index.ts
- src/execution/utils.ts
> fix: remove default access list

- .changeset/bumpy-bags-tell.md
- src/index.ts
- src/modules/index.ts
- src/modules/read.ts
- src/modules/validators/core.ts
Adds account state read functions:
* `getValidators`
* `getOwners`
* `areAttestersTrusted`
> View functions

- .changeset/petite-coins-fetch.md
- src/accounts/error.ts
- src/accounts/index.ts
- src/accounts/kernel.ts
- src/accounts/nexus.ts
- src/accounts/safe.ts
- src/execution/error.ts
- src/execution/index.ts
- src/execution/smart-session.ts
- src/execution/utils.ts
- src/index.ts
- src/orchestrator/client.ts
- src/orchestrator/error.ts
- src/orchestrator/index.ts
Defines custom `Error` classes for commom orchestrator (API), account, and execution failure modes.
> Type-safe error handling

- .changeset/moody-feet-shop.md
- src/accounts/index.ts
- src/accounts/kernel.ts
- src/accounts/nexus.ts
- src/accounts/safe.ts
- src/execution/index.ts
- src/execution/utils.ts
- src/orchestrator/client.ts
- src/orchestrator/types.ts
- test/deployment.ts
Provides the init code as part of the `setupOps` list to deploy the account.
> Account deployments

- src/index.ts
Export the registry methods `getSupportedTokens` and `getTokenAddress`.
> feat: add token registry functions

- .changeset/empty-ravens-wonder.md
> fix: add changeset

- .changeset/six-flies-dance.md
- bun.lock
- package.json
- src/package.json
> Move @rhinestone/shared-configs into package deps

- .changeset/bright-clowns-clap.md
- src/orchestrator/client.ts
- src/orchestrator/types.ts
Fix `getMaxTokenAmount ` by removing `account.delegations` when making API request.
> Fix max spendable amount

- .changeset/kind-dogs-cross.md
- src/orchestrator/types.ts
Add relay to `SettlementLayer` and `SettlementSystem`
> feat: add relay types

- .changeset/orange-buses-nail.md
- src/CHANGELOG.md
- src/accounts/index.ts
- src/package.json
Remove 7702 "already delegated" check
> Relax 7702 code check

- .changeset/mean-lizards-look.md
- src/index.ts
Expose the function to check if the account is deployed.
> Add `isDeployed` function

- .changeset/twelve-years-jump.md
- src/execution/compact.ts
- src/execution/permit2.ts
- src/orchestrator/types.ts
> feat: updated 712

- .changeset/ripe-toys-thank.md
- src/execution/index.ts
- src/execution/utils.ts
- src/index.ts
- src/orchestrator/client.ts
- src/types.ts
adds a dry run flag instead of using the simulation endpoint
> feat: add dry run flag instead of sim

- .changeset/gentle-pianos-worry.md
- src/execution/utils.ts
> fix: always send setup ops

- .changeset/gentle-cows-listen.md
- bun.lock
- src/orchestrator/client.ts
- src/package.json
Use the `fetch` built-in instead.
> Remove `axios`

- src/execution/compact.ts
- src/execution/index.ts
- src/execution/permit2.ts
- src/execution/types.ts
- src/execution/utils.ts
> Upstream sync

- .changeset/shaggy-tables-clean.md
- src/accounts/error.ts
- src/accounts/walletClient.ts
- src/index.ts
Add wallet client to account helper
> feat: add walletClientToAccount

- .changeset/young-months-train.md
- src/orchestrator/client.ts
depends on orchestrator changes
> feat: remove orch status endpoint
